version: '3.7'

services:
  backend-labxp:
    build: .
    ports:
      - "3333:3333"
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env
    command:
      - "npm"
      - "run"
      - "dev"
    depends_on:
      - db

  db:
    image: mongo:4.4.1-bionic
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
