version: '3.7'

services:
  backend-LabXP:
    build: .
    ports:
      - 3333:3333
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env
  db:
    image: mongo:4.4.1-bionic
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
