version: '3.7'

services:
  backend-labxp:
    build: .
    environment:
      - PORT=3333
      - JWT_SECRET=SECRET
      - CORS=http://localhost:3000
      - MONGO_URL=mongodb://localhost:27017/labxp
      - PROFILE_COLLECTION=profiles
    ports:
      - "3333:3333"
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env
    command:
      - "npm"
      - "run"
      - "dev"
  db:
    image: mongo:4.4.1-bionic
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
